<a href="https://colab.research.google.com/github/kal1kidan/ai-ml-journey/blob/master/ml_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

series

In [10]:
s = pd.Series([10,20,30,40,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

indexing

In [18]:
s.name = "calories"
s

apple        10
banana       20
orange       30
mango        40
pineapple    50
Name: calories, dtype: int64

In [19]:
print(s.name)

calories

In [20]:
s[0:2]

apple     10
banana    20
Name: calories, dtype: int64

In [21]:
s.index

Index(['apple', 'banana', 'orange', 'mango', 'pineapple'], dtype='object')

In [16]:
fruits=["apple", "banana", "orange", "mango","pineapple"]

In [22]:
s.index=fruits
s

apple        10
banana       20
orange       30
mango        40
pineapple    50
Name: calories, dtype: int64

In [25]:
fruit_protien = {
    "avaocado":20,
    "apple":0,
    "banana":5
}
fruit_protien

{'avaocado': 20, 'apple': 0, 'banana': 5}

In [32]:
s2=pd.Series(fruit_protien, name="protien")
s2

avaocado    20
apple        0
banana       5
Name: protien, dtype: int64

In [33]:
s2 > 1

avaocado     True
apple       False
banana       True
Name: protien, dtype: bool

In [35]:
ser = pd.Series(["a", np.nan , 1 , np.nan ,2])
ser.notnull().sum()

np.int64(3)